import {test} from 'node:test';import assert from 'node:assert/strict';import {start} from '../src/runtime.js';import {defaults,legacyConfig} from '../src/config.js';
function fixture({full=false,result={context_world:'fact',errors:{}},old=false}={}){
 const c=defaults();c.default_api_key='fake';const store=new Map([['risu_multiagent_lite_config_vault_v1',{config:legacyConfig(c)}]]);const calls=[];let unload,hook,remove=0;
 const host={pluginStorage:{getItem:async k=>store.get(k),setItem:async(k,v)=>store.set(k,v)},getArgument:async()=>'',addRisuReplacer:async(_,fn)=>{hook=fn},removeRisuReplacer:async()=>{remove++},onUnload:async fn=>{unload=fn},registerSetting:async()=>{},registerButton:async()=>{},
 nativeFetch:async(url,req)=>{calls.push({url,body:req.body&&JSON.parse(req.body)});if(url.endsWith('/runtime-config'))return old?{status:404,data:{detail:'not found'}}:{status:200,data:{context_window:3}};if(url.endsWith('/status'))return {data:{config:{context_window:3}}};return {data:result}}};
 return {host,calls,c,get hook(){return hook},get remove(){return remove},unload:()=>unload(),result,store};
}
test('Full falls back to old status and caches only runtime config for activity',async()=>{const f=fixture({full:true,old:true});const app=await start(f.host,{full:true});const m=[{role:'system',content:'settings'},...Array.from({length:100},()=>({role:'assistant',content:'old'})),{role:'user',content:'now'},{role:'assistant',content:'continue'}];await app.before(m,'model');await app.before(m,'model');assert.equal(f.calls.filter(c=>c.url.endsWith('/status')).length,1);const body=f.calls.find(c=>c.url.endsWith('/analyze')).body;assert.equal(body.chat_history.length,3);assert.equal(body.chat_history.at(-1).content,'continue');assert.equal(body.system_context,'settings');await app.dispose()});
test('partial results, empty output and disabled agents do not fabricate context',async()=>{const f=fixture();let result={context_world:'fact',errors:{plot:'failed'}};const app=await start(f.host,{analyze:async()=>result});const messages=[{role:'user',content:'now'}];assert.equal((await app.before(messages,'model')).length,2);result={context_world:'<think>hidden</think>',errors:{}};assert.deepEqual(await app.before(messages,'model'),messages);assert.equal(app.lastRun.status,'empty-no-injection');result={errors:{worldbuilding:'bad'}};assert.deepEqual(await app.before(messages,'model'),messages);await app.dispose()});
test('late registration and late analysis are disposed without injection',async()=>{const f=fixture();let resolve;f.host.addRisuReplacer=async()=>new Promise(r=>{resolve=r});const pending=start(f.host,{analyze:async()=>({context_world:'late',errors:{}})});await new Promise(r=>setTimeout(r,0));await f.unload();resolve();const app=await pending;assert.equal(f.remove,1);const m=[{role:'user',content:'current'}];assert.equal(await app.before(m,'model'),m)});
